/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
CREATE DATABASE IF NOT EXISTS `MicroChat`;
USE `MicroChat`;
DROP TABLE IF EXISTS `friend_request`;

CREATE TABLE `friend_request` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `requester_id` varchar(255) NOT NULL,
  `receiver_id` varchar(255) NOT NULL,
  `event_id` varchar(255) NOT NULL,
  `message` TEXT NOT NULL,
  `timestamp` timestamp NULL)
 ENGINE=InnoDB;

CREATE INDEX `requester_id_i`
  ON `friend_request` (`requester_id`);

CREATE INDEX `receiver_id_i`
  ON `friend_request` (`receiver_id`);

CREATE UNIQUE INDEX `event_id_i`
  ON `friend_request` (`event_id`);

