-run_mode=true
-log_file=/app/MicroChat/logs/friend.log
-log_level=0
-registry_host=http://etcd:2379
-instance_name=/friend_service/instance
-access_host=friend_server:10006
-listen_port=10006
-rpc_timeout=-1
-rpc_threads=1
-base_service=/service
-user_service=/service/user_service
-message_service=/service/message_service
-es_host=http://elasticsearch:9200/
-mysql_host=mysql
-mysql_user=root
-mysql_pswd=mysql123
-mysql_db=MicroChat
-mysql_cset=utf8mb4
-mysql_port=3306
-mysql_pool_count=4