-run_mode=true
-log_file=/app/MicroChat/logs/speech.log
-log_level=0
-registry_host=http://etcd:2379
-instance_name=/speech_service/instance
-access_host=speech_server:10001
-base_service=/service
-listen_port=10001
-rpc_timeout=-1
-rpc_threads=1
-app_id=7306672
-api_key=0WbqvaXRsqVuzD91TrXUOK0d
-secret_key=aDg4I06odqh5RUnaYXPLtmDa8jedTQ6P