-run_mode=true
-log_file=/app/MicroChat/logs/user.log
-log_level=0
-registry_host=http://etcd:2379
-instance_name=/user_service/instance
-access_host=user_server:10003
-listen_port=10003
-rpc_timeout=-1
-rpc_threads=1
-base_service=/service
-file_service=/service/file_service
-es_host=http://elasticsearch:9200/
-mysql_host=mysql
-mysql_user=root
-mysql_pswd=mysql123
-mysql_db=MicroChat
-mysql_cset=utf8mb4
-mysql_port=3306
-mysql_pool_count=4
-redis_host=redis
-redis_port=6379
-redis_db=0
-redis_keep_alive=true
